### ISSUE TITLE
Question Around Using URL To Activate Filter

### ISSUE THREAD

**Issue by MattMarble** [dettogatto/elementor-super-cat#1]
Hey!

I absolutely love this addition you have cobbled together and it has helped me out majrly on a current project. If I can get one final thing out of it I will definitely shoot you a donation for a coffee (or beverage of your choice!) I am wondering if it is possible to activate one of the filter options using the URL. For example on [my site here](http://staging.cwbts.com/courses/), I am hoping to be able to activate a filter option based on adding a class (#certificate-iii) etc to the URL. I have looked into doing this myself with some more javascript but was wondering if you already had this implemented in some way. [This](https://stackoverflow.com/questions/9983091/jquery-add-class-based-on-page-url) is what I was looking at adding.

Please let me know if this is confusing.

Cheers,
Matt

**Comment by dettogatto** [comment]
Sounds like a good thing to add. Would you rather use the hash in the url or a get variable?
(.../page#the_filter vs .../page?filter=the_filter)

**Comment by MattMarble** [comment]
In this instance the hash is preferable as my current client is copying a site with this functionality. Keeping it with hashes would satisfy him!

**Comment by dettogatto** [comment]
Enjoy and let me know if everything works okay 😸

**Comment by MattMarble** [comment]
Thanks, it is working. It seems to require the url to be page#filter and not page/#filter, which cause the page to reload each time, but at this point I am happy and the client most likely won't notice!

Keep an eye out for that beverage donation shortly! :)

**Comment by dettogatto** [comment]
The trailing slash add/removal may depend from your .htaccess file and Wordpress settings 😉
