### ISSUE TITLE
Filter only used categories

### ISSUE THREAD

**Issue by Afplaktape** [dettogatto/elementor-super-cat#12]
Hi!

First of all: Really nice plugin! helped me a lot already and saved a lot of time! 

Unfortunately I'm stuck on a problem now: I'm buidling a website where I have multiple pages that need to show posts but with different categories. For example:

page 1 - categorie 1 + 2
page 2 - categorie 3 + 4 + 5
page 3 - categorie 6

The correct posts of the selected categories are shown but the problem I'm having is that it keeps showing all the categories on every page. Is there an easy fix for this?

**Comment by dettogatto** [comment]
I'm thinking of adding an option to hide the "unused" filters. Still have no ETA, as I'm working on other stuff rn 😅

**Comment by shaneonabike** [comment]
@Afplaktape you could also submit a patch!
