### ISSUE TITLE
Multiple filters working in collaboration

### ISSUE THREAD

**Issue by shaneonabike** [dettogatto/elementor-super-cat#14]
Ok it probably seems obvious but if we have multiple categories they don't necessarily work together.

Category: Animals
- Dog
- Cat

Category: Colour
- Brown
- Black

So if I choose Brown it will filter the brown results, but then choosing Dog it won't filter it down further. If you can given me some guidance on how I could go about linking them together I would be more than happy to modify the JS to do that and supply a patch. It's a big requirement presently for my client.

**Comment by dettogatto** [comment]
This is exactly what the checkbox filter does. Just create the 2 custom taxonomies animals and colors.

**Comment by shaneonabike** [comment]
Ok it does work! Ironically, I noticed that it actually "partially" also works with the filter bar and checkbox. If I select a checkbox item first and then a filter item it works. If I select the filter bar item first and then a checkbox it doesn't work.

Ideally, I would just use the checkbox but it doesn't provide an option for All categories so in my case it wouldn't work for me. What do you think? Is it something easy that could be fixed cause I feel like you are almost there anyway with the first option I noticed.

**Comment by shaneonabike** [comment]
Is there some way you could point me and I could create a patch or debug this (more than happy to contribute again :P)

**Comment by shaneonabike** [comment]
Also, if you don't really want to add that functionality (combined) maybe direct me in a way we could add a All checkbox which when clicked it would check all boxes?

**Comment by dettogatto** [comment]
I don't get you. The checkbox filter is designed just like the ones you find on Booking.com or e-coms: all unchecked equals all checked (no filter is applied in both situations). You could add a "clean filters" button in JS unchecking all checkboxes. RN I couldn't really point you anywhere as I'm on vacation: I don't have the code with me and don't really remember if I used real checkboxes or just JS...

**Comment by shaneonabike** [comment]
Woaaa responding on your vacation! Get outside have a great vacation :)

Fair point about unchecking all of them to show All. I was more thinking if I wanted to hide the checkboxes but that's more my issue then generally for this module.

I think it would be ideal if they all just integrated together, but maybe that's too hard to make happen

**Comment by dettogatto** [comment]
What do you mean by integrate together? :)

**Comment by shaneonabike** [comment]
I mean that it would be cool if the you clicked on a link in the filter bar, and that reduced the items on the page. Then when using the checkbox(es) it would further drill down. Right now they run independantly, but what I am suggested is (like multiple checkboxes) they are aware of the other widget choices

**Comment by shaneonabike** [comment]
What do you think?

**Comment by dettogatto** [comment]
This may be incompatible with the way I scripted the filter bar, because multiple filter bars work together in another way.

But gives me an idea: I could add an option to the checkbox filter to show in a row, and, since you can already hide the checkbox and keep just the names, this would give you the ability to give the checkbox filter the same look as the filter bar. What do you think?

**Comment by shaneonabike** [comment]
Hey! I had thought about that too although my client has a constraint to not allow multiple selects (I think that's a definite awesome add-on though). Is there perhaps some custom code that I could write to link the two?

**Comment by dettogatto** [comment]
What a weird constraint, lol. Where does it come from? Just curious.

Well you could code a custom JS to make one filter consider the other when changing, i.e. making one filter hide the posts not selected by the other one after hiding its own.

**Comment by shaneonabike** [comment]
Hmmm I don't think it's that strange honestly. Take a look at this page (specifically the links section) - 

It is meant to be a //primary// filter, and then you use the checkboxes at the top to further filter it down. This is fairly standard with say Amazon where you might select a main category and then further filter down a bunch of stuff (especially where they don't want you to use multiple categories)

**Comment by dettogatto** [comment]
That's not a constraint, that's a requirement from your client then.
None of our clients need this functionality rn.

**Comment by shaneonabike** [comment]
For sure! But I also saw it as an additional feature that could contribute... Anyway I can poke around and see if there could be some contribution to be made.

BTW just to be clear I meant constraint in the terms that the widgets aren't collaborating together. Constraint meaning limitation. I guess I always just like stuff naturally just working together...

**Comment by shaneonabike** [comment]
Since the items aren't aware of each other I modified it to use two checkboxes. Then I made the checkboxes act more like a radio by using the following code. I put this hear to help others.

`document.addEventListener("DOMContentLoaded",` function(event){
  var $jq = jQuery.noConflict();
  $jq("#filter--83ecfd9 .cat-checkbox-filter").on('click', function() {
    let posts = $jq(this).attr("data-posts");
    let term = $jq(this).attr("data-term");
    $jq("#filter--83ecfd9 li.cat-checkbox-filter").each(function(){
       if ($jq(this).hasClass('elementor-active')) {
         if ($jq(this).attr("data-term") != term) { $jq(this).trigger('click'); }
       }
    });
    
  });
});`
