### ISSUE TITLE
Elementor-super- cat not working with elementor blog addon

### ISSUE THREAD

**Issue by ochristianlove** [dettogatto/elementor-super-cat#15]
can you inspect my blog page, i try using super-cat-filter with ElemenKit blog addon but  it not working [view site](https://buildwithusagency.com/blog) at the CSS ID of the post widget i used ElementsKit widget id but it not working.

Thanks

**Comment by dettogatto** [comment]
Hi! The filter bar is only designed to work with Elementor's original Posts Widget.
