### ISSUE TITLE
Problem with main/nested categories

### ISSUE THREAD

**Issue by rolffresh** [dettogatto/elementor-super-cat#18]
Hi, I am using the plugin and it is very helpful, thank you!
One issue I am facing is the following: My posts (about 300) are put in categories on difference levels, like
- cat1
-- cat 2
--- cat 3
and so on.

The filter bar does not work for categories on level 1, only for sub-categories.
Here's a screenshot for a better explanation: http://share.freshvanroot.com/ELFCRg

thanks for tips on how to fix that.

**Comment by dettogatto** [comment]
I tried to replicate your issue, but couldn't. On my Wordpress installation everything works as expected: the filter bar makes no difference between categories and sub-categories.

Maybe provide a link of the non-working page?

**Comment by rolffresh** [comment]
http://dev.linearis.at/blog/

**Comment by dettogatto** [comment]
Okay, so is there any posts with category BI Prozesse, BI Standards or BI Technologie? Are these the only main categories?

**Comment by rolffresh** [comment]
oh my bad. no!
Is it possible to hide those three categories via CSS?

**Comment by dettogatto** [comment]
If you just want to hide empty categories there is an option in the widget Filter Bar that does exactly that :D

**Comment by dettogatto** [comment]
If you want to hide specific categories, regardless if they are populated or not, you can use CSS with the `data-term` attribute. Like this:

`li[data-term="category-prozess-analyse"]
{
    display: none;
}`

**Comment by rolffresh** [comment]
ok. the option in the widget does not work, i'll try the CSS hack later today. thanks for your support

**Comment by dettogatto** [comment]
Are you sure it's now working? I can't see them on your page anymore...
