### ISSUE TITLE
SUPER CAT IS STILL NOT WORKING WITH ELEMENTOR PRO

### ISSUE THREAD

**Issue by ochristianlove** [dettogatto/elementor-super-cat#19]
i got elementor pro, the widget is still not working, please i don't know if am missing any step here, help.
www.buildwithusagency.com/blog

and again in the future can you achieve this 
https://www.growthgurus.com/blog/

filter by date and letters

**Comment by ochristianlove** [comment]
is there anything else i need too set after installation of super cat, because i have been trying different class ID  on the post filter

**Comment by dettogatto** [comment]
Inspecting your page it seems like you didn't give any CSS ID to the Posts widget and you are trying to use some classes in the filter bar. This does not work.

To make things work you need to give a CSS ID to the Posts widget (Advanced tab) and enter the same exact value in the Filter Bar.
