### ISSUE TITLE
Incorrect Filtering When Filter Options Are Extensions Of Each Other

### ISSUE THREAD

**Issue by MattMarble** [dettogatto/elementor-super-cat#2]
Hey,

I have found an issue when the filter includes options that are simply longer spellings of previous options. For example on [my page here](http://staging.cwbts.com/courses/), if you select Certificate II you also get the results of Certificate III when this taxonomy is not applied to those posts.

Thanks,
Matt

**Comment by dettogatto** [comment]
Thank you for your feedback! This issue should have been fixed in last commit 😸

**Comment by MattMarble** [comment]
Thanks so much! It does work perfectly now.
