### ISSUE TITLE
Undefined variable: settings in protected function _content_template()

### ISSUE THREAD

**Issue by Mulli** [dettogatto/elementor-super-cat#21]
I get the following error in almost (all?) widgets.
Here are 2 examples:
```
PHP Notice:  Undefined variable: settings in /elementor-super-cat-master/widgets/checkbox-filter.php on line 360
PHP Notice:  Undefined variable: settings in /elementor-super-cat-master/widgets/dropdown-filter.php on line 217

```
Tried to fix it but this function is not called from the code. 
Is it redundant?
Or just parameter setting is missing?

**Comment by dettogatto** [comment]
Please, let me know if this update fixed it as I could not get your same error.
