### ISSUE TITLE
Breaks filtering css in backend posts.

### ISSUE THREAD

**Issue by endombed** [dettogatto/elementor-super-cat#28]
First off thanks for the plugin! :)

Just for your and others consideration. 
The css in /wp-content/plugins/elementor-super-cat-master/assets/css/admin.css breaks the filtering pagination in posts page @ wordpress backend.

You set the style for all textarea and inputs in wordpress admin area.

textarea, input[type="text"], select{
  width: 100%;
}
I just commeted this out. So no worries, but it could be nice for others to know...

And also it would be nice if you could integrate this with the elementor posts pagination in some way.
Now if you have elementors pagination ON and have many pages and then you push a filter so you get just one post it still shows all the pagination links. 

Stay awesome and thanks again! :)
/Endombed

**Comment by dettogatto** [comment]
Thank your precise feedback! Should be fixed now
