### ISSUE TITLE
Extra Functionalities - extra webhooks

### ISSUE THREAD

**Issue by tomasbanik** [dettogatto/elementor-super-cat#31]
Does the _Extra Functionality - Gives you the ability to set extra webhooks for Elementor forms_ work?

I registered a new webhook in Super Cat's settings. But no extra webhook appears in a Form's Actions after submit.

Thanks in advance

**Comment by dettogatto** [comment]
It should work. You have to add the url directly in the plugin page, nothing will show up in the Elementor Form. Just provide the name of the form you want to add the webhook to and the url you want to send the request to, it should pass all the form fields. I know it's not ideal, maybe I'll change it in the future :)
Let me know if it works!

**Comment by tomasbanik** [comment]
Ah, OK, now I get it. It works. Thanks for the assistance.
Well, I think modifying the Form part is more intuitive for the end-user.
