### ISSUE TITLE
How to choose order of categories shown in the filter bar ? 

### ISSUE THREAD

**Issue by vanocreations** [dettogatto/elementor-super-cat#34]
Hi there !
Thank you for this filter bar for post widget ! Really usefull.

I would like to force my taxonomies shown in the filter bar in a certain order. 
Actually it is showed by A to Z.

Example :
What i have now : SEE ALL / LOGOTYPE / PRINTS / WEB
Order i would like : PRINTS / WEB / LOGOTYPE / SEE ALL

Is there a way to achieve this ?
Thanks for support.

**Comment by vanocreations** [comment]
Finally managed to do it using sort by slug and giving slug names like 01-prints / 02-web ...

**Comment by dettogatto** [comment]
Yes, you found the intended way. I purposefully used the slugs for sorting so that you are able to change the order and still have a nice printed name :)
