### ISSUE TITLE
Is there a way I could get filterbar working with Woocommerce Products widget instead of posts widget?

### ISSUE THREAD

**Issue by rolffresh** [dettogatto/elementor-super-cat#35]
Hi, I have added the filterbar to a site and it works well for months.
The same site runs Woocommerce, and  I would like to have the same functionality of the filterbar applied to Woocommerce products.
Would that be possible, and if yes, what do I need to do?
thanks for any tips.
-rolf

**Comment by dettogatto** [comment]
I looked into it and found there is a way, with the plugin as it is rn.
Just use the Elementor Posts widget to show the products (change the Source in the Query tab) and everything else should be the same, except you have to choose the `Product categories` taxonomy in the Filter Bar options 😄 
Let me know if you get it to work!
