### ISSUE TITLE
Multiple filters on same page

### ISSUE THREAD

**Issue by shaneonabike** [dettogatto/elementor-super-cat#4]
Hey! First off thanks for an awesome plugin!

So I got this working just fine, but found a little glitch. In our situation we need to filter by two different taxonomies. Therefore, I placed one in a column on the left and another above the content.

What's interesting is that it would appear as though all the terms are appearing but being placed in the left column...

![Selection_001](https://user-images.githubusercontent.com/1126026/58274329-0591f380-7d69-11e9-81ee-6877612cd94e.jpg)

~~Also, when these are injected together it stops displaying all the results. Perhaps it's the limit of the actual portfolio code that you rewrote?~~

**Comment by shaneonabike** [comment]
Actually, even if I put the same taxonomy (as a workaround for maybe it not working properly with two seperate) it still injects them together....

**Comment by dettogatto** [comment]
I'll make a quick fix, thank you for reporting!

**Comment by shaneonabike** [comment]
Wow awesome works like a charm thanks so much. I was already writing a patch but your solution is way more elegant!
