### ISSUE TITLE
JS Error with standard jQuery

### ISSUE THREAD

**Issue by rnsrv** [dettogatto/elementor-super-cat#45]
I registered standard jQuery (to always have the current version) and deregistered the default wordpress jQuery. Some of my elements (including the GDPR-Consent-Tool) use jQuery to show and hide conditionally with the $-identifier. Unfortunately these do not work on pages where I included the super-cat filter and i get several errors ($ is not a function). I guess this is because the filter depends on the wordpress default no-conflict jQuery. 

Is there any way to circumvent this without rewriting the whole theme?

Thank you for your help

**Comment by dettogatto** [comment]
Could you link me the page where you are having the issue? So that I can take a look at the console for errors :)

**Comment by rnsrv** [comment]
Sure, I quickly threw together a test page:
Page with Super Cat: https://wp-test.basisentwicklung.de/supercat-test/ (errors and consent-tool doesn't open)
Page without Super Cat: https://wp-test.basisentwicklung.de/consent-test/ (no errors and consent-tool opens)

**Comment by dettogatto** [comment]
Can you try to replace the code of the file in `SuperCat/assets/js/post-filter.js` via the Plugin Editor with this:
```
(function($){
  
  $(document).ready(function(){
    
    $(".super-cat-post-filter").each(function(){
      let container = $("#" + $(this).attr("data-container"));
      let posts = $(this).attr("data-posts");
      let term = $(this).attr("data-term");
      if(term != "" && container.attr("data-hide-empty") == "yes"){
        if($("#"+posts).find('article.' + term).length < 1){
          $(this).hide();
        }
      }
    });
    
    $(".super-cat-post-filter").click(function(event){
      let item = $(event.target);
      let term = item.attr("data-term");
      let posts = item.attr("data-posts");
      
      // hide all
      $("#"+posts).find('article').hide();
      // set all to inactive
      $(".super-cat-post-filter").removeClass("elementor-active");
      
      // sync option in Dropdown Filters
      $('.super-cat-dropdown-list').each(function(){
        let toSelect = $(this).find('option[data-term="' + term + '"]');
        if(toSelect.size() > 0){
          toSelect.attr('selected','selected');
        }else{
          $(this).find('option[data-term=""]').attr('selected','selected');
        }
      });
      
      // Show / Hide all
      if (term == '') {
        // show all
        history.replaceState(null, null, ' ');
        $("#"+posts).find('article').fadeIn(400);
        $('.super-cat-post-filter[data-term=""]').addClass("elementor-active");
      } else {
        // show some
        $('.super-cat-post-filter[data-term="' + term + '"]').addClass("elementor-active");
        window.location.hash = "#" + term;
        $("#"+posts).find('article.' + term).fadeIn(400);
      }
    });
    
    if(window.location.hash){
      let hhh = window.location.hash.replace("#", "");
      $( 'li.elementor-portfolio__filter[data-term='+hhh+']' ).trigger("click");
    }
    
  });
  
})(jQuery);
```

If it works I'll release un update to address this issue.

However it is good practice to check that jQuery was loaded before running your jQuery-dependent code. You could solve this just by putting `(function($){ /* Your code here */ })(jQuery);` around your JS in your theme file `bwm_template/js/script-custom.js` .
Another thing you should make sure to do on WP is to include dependencies, such as jQuery, in your call to `wp_register_script()` (or `wp_enqueue_script()`)

**Comment by rnsrv** [comment]
Included it directly in the live environment - works perfectly, thank you! 
Now everything is loading fine.

Thank you for your tip on the no-conflict jquery. I included that, too.

**Comment by rnsrv** [comment]
Included it directly in the live environment - works perfectly, thank you! 
Now everything is loading fine.

Thank you for your tip on the no-conflict jquery. I included that, too.

**Comment by dettogatto** [comment]
Perfect! Next week, when I'll get back home, I will release an update :)
