### ISSUE TITLE
Listing using slug rather than actual name

### ISSUE THREAD

**Issue by shaneonabike** [dettogatto/elementor-super-cat#5]
I noticed that the plugin is actually using the slug as the display name for the filter. I'm building a French website so this isn't going to work so well. Also, when people have random slugs like myslug123 it appears as that.

I'll try and see if I can figure out where this is going wrong to help fix it. Thanks for an awesome plugin

**Comment by dettogatto** [comment]
Yes, nothing is wrong, it is supposed to use the slug as everything is built with JS. I just needed it quick, so did not put the effort into retrieving the Taxonomies with PHP.

I'll consider changing this when I'll have more time to put into this.

This is also why I didn't push this plugin to Wordpress: I don't like it enough yet 😅

**Comment by dettogatto** [comment]
Ignore me, actually I'm on it 😸
