### ISSUE TITLE
Awesome plugin

### ISSUE THREAD

**Issue by donderjager** [dettogatto/elementor-super-cat#6]
Thanks for creating this free plugin. Now I can filter my posts.

Let's say I'm have posts about toys and tags with cars and dolls. I'm now within my Car category. But the archive is still showing Dolls tags. 

Is there a way to not show the dolls tag?

**Comment by dettogatto** [comment]
I'm a little confused, I didn't understand the question 😅
Do you want to hide the "filtering" element from the filter bar or some posts with a certain tag?
Maybe you could provide an example page and tell me how you'd like it to work 😸

**Comment by donderjager** [comment]
Hi Nicola,

For example
https://quiza.nl/quiz/the-walking-dead/

The filter options are showing all my post taxonomy's. The Walking Dead post has the following taxonomy's.

**Tag:**
The Walking Dead

But it is also showing another tag "Star Wars" from another post.

I hope it's clear now. Thanks!

**Comment by dettogatto** [comment]
At the moment the Filter Bar shows all non-empty Tags / Categories / Taxonomies, disregarding the Query option in the Portfolio.

If I understood correctly you want to hide the taxonomies with no post appearing on the page, right?
