### ISSUE TITLE
Dropdown select for responsive mobile option

### ISSUE THREAD

**Issue by shaneonabike** [dettogatto/elementor-super-cat#7]
I see that you added checkboxes recently which are also amazing! Thanks for your really hard work on this project.

I was also wondering if there is any chance that you could create another option which was a selection box output. I'm primarily thinking for mobile devices having links is not always that ideal. I mean it would be ubber amazing if this just changed from a list to a select box in mobile, but I feel that's a lot to ask.

What are your thoughts?

**Comment by dettogatto** [comment]
I think this is a nice input! I didn't think about responsivity and that's very bad from me 😹
Could you perhaps link some graphic examples of how you imagined it? That would be very helpful!

**Comment by shaneonabike** [comment]
It's normal! But on most mobile systems we really don't want select links because it just clogs the interface. Here's an example:
![Selection_004](https://user-images.githubusercontent.com/1126026/59101100-63444500-88fe-11e9-87ae-215b3c4a45cf.jpg)

I think that the basic idea is the following:

* Provide an admin toggle whereby they can display the select instead of the links on mobile. Elementor already provides these settings for you
* Add to your css the hide / show for mobile
* Render the select box if they have chosen for it to degrade on mobile

You could even allow this for tablet if you so wish, but for my purposes normally I just need it on mobile

**Comment by shaneonabike** [comment]
I think it could also be useful to provide a placeholder option field too I guess

**Comment by shaneonabike** [comment]
Or an even easier approach would for you to create another widget that is a select and we could handle the appropriate theming if all the rest is too much

**Comment by shaneonabike** [comment]
Is there any place that you could direct me and I could even write a patch to create a select case. If you give me an idea i"m happy to code a portion of this?

**Comment by shaneonabike** [comment]
Hey @dettogatto ! I still need to resolve this issue and would love to contribute. I just need you to point me in the direction of where I should generate this... Unless you are less keen?

**Comment by dettogatto** [comment]
If you want to give it a try all the code for the Filter Bar widget is in /widgets/post-filter.php

There is no CSS as I used the same Classes Elementor puts on the original filter bar (the one for the Portfolio Widget)

I see 2 solutions, 1 more elegant than the other.

First, easy but inelegant would be to duplicate the widget, make it look like you want it on mobile, putting both on the page and hide one or the other accordingly to page size, via Elementor.

The other one would be to make the original widget responsive, tweaking its HTML, maybe adding a control to switch on/off the responsivity.

**Comment by shaneonabike** [comment]
Perfect! I think the only effective solution (that is also clean) is to provide a dropdown that generates the same functionality. We could then leave it up to the developer to integrate it for mobile or not. I am going to create a new widget that does that cloning your checkbox one. Then I'll update this ticket with the patch.

**Comment by shaneonabike** [comment]
#10 I added a pull request with the code that is modified. You can try it out and let me know what you think. I suspect the JS could be simplified even more for performance.

**Comment by dettogatto** [comment]
Everything should be working now.
The dropdown and the filter bar even sync to each other, regardless if they are visible or not.
Try it out and let me know what you think 😸

**Comment by shaneonabike** [comment]
Cool glad to hear that you liked the merge! I don't know if you simplified the JS I added as I found it a little inefficient but didn't have the time to tweak it. Anyway, happy that it's rolling along nicely!

**Comment by dettogatto** [comment]
Yes, I've rewritten the JS, should be silk smooth.
