### ISSUE TITLE
JS optimization

### ISSUE THREAD

**Issue by shaneonabike** [dettogatto/elementor-super-cat#9]
Hey

Just a quick note that perhaps an optimization would be to place the JS code directly into an external file and use wordpress code to attach that on pages that include the widgets. The reason being is that plugins like WP Rocket and W3 Total Cache are able to compress these files into much smaller versions (or you could also do that yourself).

It's not a huge requirement but just some code feedback that can improve performance.

**Comment by dettogatto** [comment]
Yes, nice input. Thanks!
